### ISSUE TITLE
Where's the "update app" modal?

### ISSUE THREAD

**Issue by kilianso** [mike-tuxedo/svelte-ios-pwa#2]
Hello, thanks for this great repo!

I'm not sure if I have overseen this, but where exactly do you show that "update app" modal? 
And would it trigger every time the PWA is opened on visibilityChange, even if it was running in the background?

My concern is, at least as far as I know, you cannot trigger an update of the service worker if the PWA is running on an iOS homescreen if the user has not "hard-quit" the app, right?

**Comment by mike-tuxedo** [comment]
I'm sorry, this was a wrong information in the README, i removed this line.
I had it implemented in my private app, but can't get it to work, at the moment, in this example app.

**Comment by kilianso** [comment]
Ah okay I see. Well, it really doesn`t seem that easy to achieve it on iOS at the moment.

One approach I found is to register the `visibilityChange` event as soon as the service worker is installed and then trigger it every time the PWA comes into "focus".

https://stackoverflow.com/a/55612041/4168960

I thought I would leave this here just in case you are still interested in finding a solution.

**Comment by mike-tuxedo** [comment]
Great, thank you!
